// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_mK8nNkHQh4vZLGV-AcodFuv_Z1wyx9k',
    appId: '1:150543509218:web:da5056e161051a1c3760bb',
    messagingSenderId: '150543509218',
    projectId: 'transcriber-2a15d',
    authDomain: 'transcriber-2a15d.firebaseapp.com',
    storageBucket: 'transcriber-2a15d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLFJN9YrBOIEyJmcFRLuyNuBWJVScLIYs',
    appId: '1:150543509218:android:3a75418445983be93760bb',
    messagingSenderId: '150543509218',
    projectId: 'transcriber-2a15d',
    storageBucket: 'transcriber-2a15d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAONPpLP-SgTHR3Jzc2QbQL5W_hRtirqg8',
    appId: '1:150543509218:ios:507f8ce5113fa37c3760bb',
    messagingSenderId: '150543509218',
    projectId: 'transcriber-2a15d',
    storageBucket: 'transcriber-2a15d.appspot.com',
    iosBundleId: 'com.sokmen.audioTranscripter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAONPpLP-SgTHR3Jzc2QbQL5W_hRtirqg8',
    appId: '1:150543509218:ios:507f8ce5113fa37c3760bb',
    messagingSenderId: '150543509218',
    projectId: 'transcriber-2a15d',
    storageBucket: 'transcriber-2a15d.appspot.com',
    iosBundleId: 'com.sokmen.audioTranscripter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_mK8nNkHQh4vZLGV-AcodFuv_Z1wyx9k',
    appId: '1:150543509218:web:234762ae60c17bce3760bb',
    messagingSenderId: '150543509218',
    projectId: 'transcriber-2a15d',
    authDomain: 'transcriber-2a15d.firebaseapp.com',
    storageBucket: 'transcriber-2a15d.appspot.com',
  );
}
